/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package User;

import Controller.Controller;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Suad's Laptop
 */
public class ChangeLoginInfo extends javax.swing.JInternalFrame {

    private User currentUserInfo = null;

    /**
     * Creates new form ChangeLoginInfo
     *
     * @param currentUserInfo
     * @throws java.sql.SQLException
     */
    public ChangeLoginInfo(User currentUserInfo) throws SQLException {
        initComponents();
        this.currentUserInfo = currentUserInfo;
        startup();
        escapeKey();
    }
    
    private void startup() {
        userIdLabel.setText(Integer.toString(currentUserInfo.getId_user()));
        userNameLabel.setText(currentUserInfo.getIme());
        userSurnameLabel.setText(currentUserInfo.getPrezime());
        userPrivillegeLabel.setText(currentUserInfo.getOvlasti());
    }
    
    private void escapeKey() {
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = getRootPane().getActionMap();

        Action escapeAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        };

        inputMap.put(KeyStroke.getKeyStroke("ESCAPE"), "disposeForm");
        actionMap.put("disposeForm", escapeAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        userIdLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userSurnameLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        userPrivillegeLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        currentPasswordInput = new javax.swing.JPasswordField();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        newPasswordInput = new javax.swing.JPasswordField();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        verificationPasswordInput = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        changeBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pristupni podaci");
        setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setText("Izmjena pristupnih podataka");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(8, 1, 0, 8));

        jPanel2.setMaximumSize(new java.awt.Dimension(302, 28));
        jPanel2.setMinimumSize(new java.awt.Dimension(302, 28));
        jPanel2.setPreferredSize(new java.awt.Dimension(302, 28));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setText("ID zaposlenika:");
        jLabel11.setMaximumSize(new java.awt.Dimension(150, 28));
        jLabel11.setMinimumSize(new java.awt.Dimension(150, 28));
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel2.add(jLabel11, gridBagConstraints);

        userIdLabel.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        userIdLabel.setMaximumSize(new java.awt.Dimension(150, 28));
        userIdLabel.setMinimumSize(new java.awt.Dimension(150, 28));
        userIdLabel.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        jPanel2.add(userIdLabel, gridBagConstraints);

        jPanel1.add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(302, 28));
        jPanel3.setMinimumSize(new java.awt.Dimension(302, 28));
        jPanel3.setPreferredSize(new java.awt.Dimension(302, 28));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel1.setText("Ime:");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 28));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 28));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel3.add(jLabel1, gridBagConstraints);

        userNameLabel.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        userNameLabel.setMaximumSize(new java.awt.Dimension(150, 28));
        userNameLabel.setMinimumSize(new java.awt.Dimension(150, 28));
        userNameLabel.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        jPanel3.add(userNameLabel, gridBagConstraints);

        jPanel1.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(302, 28));
        jPanel4.setMinimumSize(new java.awt.Dimension(302, 28));
        jPanel4.setPreferredSize(new java.awt.Dimension(302, 28));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setText("Prezime:");
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 28));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 28));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel4.add(jLabel3, gridBagConstraints);

        userSurnameLabel.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        userSurnameLabel.setMaximumSize(new java.awt.Dimension(150, 28));
        userSurnameLabel.setMinimumSize(new java.awt.Dimension(150, 28));
        userSurnameLabel.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        jPanel4.add(userSurnameLabel, gridBagConstraints);

        jPanel1.add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(302, 28));
        jPanel5.setMinimumSize(new java.awt.Dimension(302, 28));
        jPanel5.setPreferredSize(new java.awt.Dimension(302, 28));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setText("Ovlasti:");
        jLabel10.setMaximumSize(new java.awt.Dimension(150, 28));
        jLabel10.setMinimumSize(new java.awt.Dimension(150, 28));
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel5.add(jLabel10, gridBagConstraints);

        userPrivillegeLabel.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        userPrivillegeLabel.setMaximumSize(new java.awt.Dimension(150, 28));
        userPrivillegeLabel.setMinimumSize(new java.awt.Dimension(150, 28));
        userPrivillegeLabel.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        jPanel5.add(userPrivillegeLabel, gridBagConstraints);

        jPanel1.add(jPanel5);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel16.setText("Trenutna lozinka:");
        jLabel16.setMaximumSize(new java.awt.Dimension(150, 28));
        jLabel16.setMinimumSize(new java.awt.Dimension(150, 28));
        jLabel16.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel10.add(jLabel16, gridBagConstraints);

        currentPasswordInput.setMaximumSize(new java.awt.Dimension(150, 28));
        currentPasswordInput.setMinimumSize(new java.awt.Dimension(150, 28));
        currentPasswordInput.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        jPanel10.add(currentPasswordInput, gridBagConstraints);

        jPanel1.add(jPanel10);

        jPanel11.setMaximumSize(new java.awt.Dimension(302, 28));
        jPanel11.setMinimumSize(new java.awt.Dimension(302, 28));
        jPanel11.setPreferredSize(new java.awt.Dimension(302, 28));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel17.setText("Nova lozinka:");
        jLabel17.setMaximumSize(new java.awt.Dimension(150, 28));
        jLabel17.setMinimumSize(new java.awt.Dimension(150, 28));
        jLabel17.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel11.add(jLabel17, gridBagConstraints);

        newPasswordInput.setMaximumSize(new java.awt.Dimension(150, 28));
        newPasswordInput.setMinimumSize(new java.awt.Dimension(150, 28));
        newPasswordInput.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        jPanel11.add(newPasswordInput, gridBagConstraints);

        jPanel1.add(jPanel11);

        jPanel12.setMaximumSize(new java.awt.Dimension(302, 28));
        jPanel12.setMinimumSize(new java.awt.Dimension(302, 28));
        jPanel12.setPreferredSize(new java.awt.Dimension(302, 28));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jLabel18.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel18.setText("Potvrda lozinke:");
        jLabel18.setMaximumSize(new java.awt.Dimension(150, 28));
        jLabel18.setMinimumSize(new java.awt.Dimension(150, 28));
        jLabel18.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel12.add(jLabel18, gridBagConstraints);

        verificationPasswordInput.setMaximumSize(new java.awt.Dimension(150, 28));
        verificationPasswordInput.setMinimumSize(new java.awt.Dimension(150, 28));
        verificationPasswordInput.setPreferredSize(new java.awt.Dimension(150, 28));
        verificationPasswordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                verificationPasswordInputKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        jPanel12.add(verificationPasswordInput, gridBagConstraints);

        jPanel1.add(jPanel12);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        cancelBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cancelBtn.setText("Otkaži");
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.setMaximumSize(new java.awt.Dimension(96, 28));
        cancelBtn.setMinimumSize(new java.awt.Dimension(96, 28));
        cancelBtn.setPreferredSize(new java.awt.Dimension(96, 28));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel7.add(cancelBtn, gridBagConstraints);

        changeBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        changeBtn.setText("Promijeni");
        changeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeBtn.setMaximumSize(new java.awt.Dimension(96, 28));
        changeBtn.setMinimumSize(new java.awt.Dimension(96, 28));
        changeBtn.setPreferredSize(new java.awt.Dimension(96, 28));
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        jPanel7.add(changeBtn, gridBagConstraints);

        jPanel1.add(jPanel7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        Controller dbController = new Controller();
        if (currentPasswordInput.getText().isEmpty() || newPasswordInput.getText().isEmpty()
                || verificationPasswordInput.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ispunite sva polja!", "Greška", JOptionPane.ERROR_MESSAGE);
        } else {
            if (currentPasswordInput.getText().equals(currentUserInfo.getPassword())) {
                if (newPasswordInput.getText().equals(verificationPasswordInput.getText())) {
                    if (newPasswordInput.getText().equals(currentPasswordInput.getText())) {
                        JOptionPane.showMessageDialog(rootPane, "Nova lozinka ne može biti stara lozinka.", "Greška", JOptionPane.ERROR_MESSAGE);
                    } else {
                        String sql = "UPDATE Zaposlenik SET password = " + newPasswordInput.getText() + " WHERE id_zaposlenik = " + Integer.toString(currentUserInfo.getId_user());
                        try {
                            if (dbController.InsDelUpd(sql)) {
                                currentUserInfo.setPassword(newPasswordInput.getText());
                                JOptionPane.showMessageDialog(rootPane, "Uspješno izmijenjena lozinka...");
                                this.dispose();
                            } else {
                                SQLException ex = new SQLException();
                                throw ex;
                            }
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Greška u postavljanju nove lozinke... Pokušajte ponovo.", "Greška", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Nove lozinke se ne poklapaju!", "Greška", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Trenutna lozinka nije tačna!", "Greška", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_changeBtnActionPerformed

    private void verificationPasswordInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificationPasswordInputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            changeBtn.doClick();
        }
    }//GEN-LAST:event_verificationPasswordInputKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton changeBtn;
    private javax.swing.JPasswordField currentPasswordInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField newPasswordInput;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userPrivillegeLabel;
    private javax.swing.JLabel userSurnameLabel;
    private javax.swing.JPasswordField verificationPasswordInput;
    // End of variables declaration//GEN-END:variables
}
