/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Item;

import Distributor.*;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Suad's Laptop
 */
public class AddNewItem extends javax.swing.JInternalFrame {
    
    private final DistributorController distributorController = new DistributorController();
    private final ItemController itemController = new ItemController();
    
    private final String currentUserId;
    private final String currentStoreId;

    /**
     * Creates new form ChangeLoginInfo
     *
     * @param currentUserId
     * @param currentStoreId
     * @throws java.sql.SQLException
     */
    public AddNewItem(String currentUserId, String currentStoreId) throws SQLException {
        initComponents();
        this.currentUserId = currentUserId;
        this.currentStoreId = currentStoreId;
        
        startup();
        escapeKey();
    }

    private void startup() throws SQLException {
        ArrayList<Distributor> allDistributors = distributorController.distributorsByUser(currentUserId, currentStoreId, "");
        
        for (Distributor distributor : allDistributors) {
            distributorInput.addItem(Integer.toString(distributor.getId_distributer()) + " - " + distributor.getNaziv());
        }
    }

    private void escapeKey() {
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = getRootPane().getActionMap();

        Action escapeAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cancelBtn.doClick();
            }
        };

        inputMap.put(KeyStroke.getKeyStroke("ESCAPE"), "disposeForm");
        actionMap.put("disposeForm", escapeAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        itemNameInput = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        distributorInput = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        amountInput = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        discountInput = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        purchasePriceinput = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        sellingPriceInput = new javax.swing.JTextField();
        buttonsPanel = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Dodaj novi artikal");
        setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Menu Icons/info.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(332, 280));
        jPanel1.setMinimumSize(new java.awt.Dimension(332, 280));
        jPanel1.setPreferredSize(new java.awt.Dimension(332, 280));
        jPanel1.setLayout(new java.awt.GridLayout(6, 0));

        jPanel6.setMaximumSize(new java.awt.Dimension(250, 28));
        jPanel6.setMinimumSize(new java.awt.Dimension(250, 28));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 28));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel12.setText("Naziv:");
        jLabel12.setMaximumSize(new java.awt.Dimension(110, 28));
        jLabel12.setMinimumSize(new java.awt.Dimension(110, 28));
        jLabel12.setPreferredSize(new java.awt.Dimension(110, 28));
        jPanel6.add(jLabel12, new java.awt.GridBagConstraints());

        itemNameInput.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        itemNameInput.setMaximumSize(new java.awt.Dimension(200, 28));
        itemNameInput.setMinimumSize(new java.awt.Dimension(200, 28));
        itemNameInput.setPreferredSize(new java.awt.Dimension(200, 28));
        jPanel6.add(itemNameInput, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel6);

        jPanel7.setMaximumSize(new java.awt.Dimension(250, 28));
        jPanel7.setMinimumSize(new java.awt.Dimension(250, 28));
        jPanel7.setPreferredSize(new java.awt.Dimension(250, 28));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel15.setText("Distributer:");
        jLabel15.setMaximumSize(new java.awt.Dimension(110, 28));
        jLabel15.setMinimumSize(new java.awt.Dimension(110, 28));
        jLabel15.setPreferredSize(new java.awt.Dimension(110, 28));
        jPanel7.add(jLabel15, new java.awt.GridBagConstraints());

        distributorInput.setMaximumSize(new java.awt.Dimension(200, 28));
        distributorInput.setMinimumSize(new java.awt.Dimension(200, 28));
        distributorInput.setPreferredSize(new java.awt.Dimension(200, 28));
        jPanel7.add(distributorInput, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel7);

        jPanel10.setMaximumSize(new java.awt.Dimension(250, 28));
        jPanel10.setMinimumSize(new java.awt.Dimension(250, 28));
        jPanel10.setPreferredSize(new java.awt.Dimension(250, 28));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel16.setText("Količina:");
        jLabel16.setMaximumSize(new java.awt.Dimension(110, 28));
        jLabel16.setMinimumSize(new java.awt.Dimension(110, 28));
        jLabel16.setPreferredSize(new java.awt.Dimension(110, 28));
        jPanel10.add(jLabel16, new java.awt.GridBagConstraints());

        amountInput.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        amountInput.setMaximumSize(new java.awt.Dimension(200, 28));
        amountInput.setMinimumSize(new java.awt.Dimension(200, 28));
        amountInput.setPreferredSize(new java.awt.Dimension(200, 28));
        jPanel10.add(amountInput, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel10);

        jPanel11.setMaximumSize(new java.awt.Dimension(250, 28));
        jPanel11.setMinimumSize(new java.awt.Dimension(250, 28));
        jPanel11.setPreferredSize(new java.awt.Dimension(250, 28));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel17.setText("Popust:");
        jLabel17.setMaximumSize(new java.awt.Dimension(110, 28));
        jLabel17.setMinimumSize(new java.awt.Dimension(110, 28));
        jLabel17.setPreferredSize(new java.awt.Dimension(110, 28));
        jPanel11.add(jLabel17, new java.awt.GridBagConstraints());

        discountInput.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        discountInput.setMaximumSize(new java.awt.Dimension(200, 28));
        discountInput.setMinimumSize(new java.awt.Dimension(200, 28));
        discountInput.setPreferredSize(new java.awt.Dimension(200, 28));
        jPanel11.add(discountInput, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel11);

        jPanel12.setMaximumSize(new java.awt.Dimension(250, 28));
        jPanel12.setMinimumSize(new java.awt.Dimension(250, 28));
        jPanel12.setPreferredSize(new java.awt.Dimension(250, 28));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jLabel18.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel18.setText("Nabavna cijena:");
        jLabel18.setMaximumSize(new java.awt.Dimension(110, 28));
        jLabel18.setMinimumSize(new java.awt.Dimension(110, 28));
        jLabel18.setPreferredSize(new java.awt.Dimension(110, 28));
        jPanel12.add(jLabel18, new java.awt.GridBagConstraints());

        purchasePriceinput.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        purchasePriceinput.setMaximumSize(new java.awt.Dimension(200, 28));
        purchasePriceinput.setMinimumSize(new java.awt.Dimension(200, 28));
        purchasePriceinput.setPreferredSize(new java.awt.Dimension(200, 28));
        jPanel12.add(purchasePriceinput, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel12);

        jPanel13.setMaximumSize(new java.awt.Dimension(250, 28));
        jPanel13.setMinimumSize(new java.awt.Dimension(250, 28));
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 28));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jLabel19.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel19.setText("Prodajna cijena:");
        jLabel19.setMaximumSize(new java.awt.Dimension(110, 28));
        jLabel19.setMinimumSize(new java.awt.Dimension(110, 28));
        jLabel19.setPreferredSize(new java.awt.Dimension(110, 28));
        jPanel13.add(jLabel19, new java.awt.GridBagConstraints());

        sellingPriceInput.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        sellingPriceInput.setMaximumSize(new java.awt.Dimension(200, 28));
        sellingPriceInput.setMinimumSize(new java.awt.Dimension(200, 28));
        sellingPriceInput.setPreferredSize(new java.awt.Dimension(200, 28));
        jPanel13.add(sellingPriceInput, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel13);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(28, 0, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        buttonsPanel.setMaximumSize(new java.awt.Dimension(360, 28));
        buttonsPanel.setMinimumSize(new java.awt.Dimension(360, 28));
        buttonsPanel.setPreferredSize(new java.awt.Dimension(360, 28));
        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        cancelBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cancelBtn.setText("Otkaži");
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.setMaximumSize(new java.awt.Dimension(96, 28));
        cancelBtn.setMinimumSize(new java.awt.Dimension(96, 28));
        cancelBtn.setPreferredSize(new java.awt.Dimension(96, 28));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        buttonsPanel.add(cancelBtn, gridBagConstraints);

        addBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        addBtn.setText("Dodaj");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.setMaximumSize(new java.awt.Dimension(96, 28));
        addBtn.setMinimumSize(new java.awt.Dimension(96, 28));
        addBtn.setPreferredSize(new java.awt.Dimension(96, 28));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        buttonsPanel.add(addBtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 16, 0);
        getContentPane().add(buttonsPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (!itemNameInput.getText().isEmpty() || !amountInput.getText().isEmpty() || !purchasePriceinput.getText().isEmpty() || !sellingPriceInput.getText().isEmpty()) {
            Item newItem = new Item();
            
            newItem.setId_distributor(Integer.parseInt(distributorInput.getSelectedItem().toString().split("\\s+")[0]));
            newItem.setNaziv(itemNameInput.getText());
            newItem.setKolicina(Integer.parseInt(amountInput.getText()));
            newItem.setPopust(Double.parseDouble(discountInput.getText()));
            newItem.setCijena_nabavke(Double.parseDouble(purchasePriceinput.getText()));
            newItem.setCijena_prodaje(Double.parseDouble(sellingPriceInput.getText()));
            
            try {
                if (itemController.addNewItem(newItem)) {
                    JOptionPane.showMessageDialog(rootPane, "Uspješno dodan novi artikal.", "Obavijest", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    SQLException ex = new SQLException();
                    throw ex;
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Greška tokom dodavanja artikla.", "Greška", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Molimo popunite sva polja.", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField amountInput;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField discountInput;
    private javax.swing.JComboBox<String> distributorInput;
    private javax.swing.JTextField itemNameInput;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField purchasePriceinput;
    private javax.swing.JTextField sellingPriceInput;
    // End of variables declaration//GEN-END:variables
}
