/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import User.UserController;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Suad's Laptop
 */
public class ForgottenPass extends javax.swing.JFrame {
    
    /**
     * Creates new form ForgottenPass
     * @throws java.sql.SQLException
     */
    public ForgottenPass() throws SQLException {
        initComponents();
        escapeKey();
        
        User.UserController userController = new UserController();
        Map<String, String> superAdminInfo = userController.superAdminInfo();
        
        name.setText(superAdminInfo.get("ime"));
        contactInfo.setText(superAdminInfo.get("kontakt"));
        setFocusable(true);
        setFocusTraversalKeysEnabled(false);
    }
    
    private void escapeKey() {
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = getRootPane().getActionMap();

        Action escapeAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                goBack.doClick();
            }
        };

        inputMap.put(KeyStroke.getKeyStroke("ESCAPE"), "disposeForm");
        actionMap.put("disposeForm", escapeAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        adminInfo = new javax.swing.JPanel();
        contactInfo = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        goBack = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zaboravljena lozinka");
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel4.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel4.setLayout(new java.awt.GridLayout(3, 0));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel2.setText("Zaboravljeni podaci za prijavu?");
        jPanel1.add(jLabel2, new java.awt.GridBagConstraints());

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel1.setText("Bez brige, kontaktirajte našeg superadministratora...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jPanel4.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        adminInfo.setLayout(new java.awt.GridBagLayout());

        contactInfo.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        adminInfo.add(contactInfo, gridBagConstraints);

        name.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        adminInfo.add(name, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 16, 0);
        jPanel2.add(adminInfo, gridBagConstraints);

        jPanel4.add(jPanel2);

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        goBack.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        goBack.setText("Nazad");
        goBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goBack.setMaximumSize(new java.awt.Dimension(81, 28));
        goBack.setMinimumSize(new java.awt.Dimension(81, 28));
        goBack.setPreferredSize(new java.awt.Dimension(81, 28));
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        jPanel3.add(goBack, gridBagConstraints);

        okBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        okBtn.setText("OK");
        okBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okBtn.setMaximumSize(new java.awt.Dimension(81, 28));
        okBtn.setMinimumSize(new java.awt.Dimension(81, 28));
        okBtn.setPreferredSize(new java.awt.Dimension(81, 28));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        jPanel3.add(okBtn, gridBagConstraints);

        jPanel4.add(jPanel3);

        getContentPane().add(jPanel4, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        Login loginFrame = new Login();
        this.dispose();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_goBackActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_okBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ForgottenPass().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(ForgottenPass.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminInfo;
    private javax.swing.JLabel contactInfo;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel name;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables
}
